<a href="https://colab.research.google.com/github/MagdaSousa/Estudo_Pandas/blob/master/Pandas_Udemy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Estudo da biblioteca Pandas, utilizando-a na análise, limpeza e obtenção de informações através dos dados.

In [1]:
import pandas as pd
import numpy as np


In [2]:
series =pd.Series([7,4,2,np.nan,6,9])

In [3]:
series
# os indices representam o tempo, e ao lado são os valores atribuídos a cada tempo

0    7.0
1    4.0
2    2.0
3    NaN
4    6.0
5    9.0
dtype: float64

In [4]:
type(series)

pandas.core.series.Series

In [5]:
data = pd.date_range('20180101',periods =6)
#periods, está relacionado a dias (freq='D').Mas  a frequencia pode ser alterada
# date_range é utilizado para manipulação de datas a partir de um período, aqui estou dizendo que quero visualizar o mes 01 no dia 01 de 2018

In [6]:
data

DatetimeIndex(['2018-01-01', '2018-01-02', '2018-01-03', '2018-01-04',
               '2018-01-05', '2018-01-06'],
              dtype='datetime64[ns]', freq='D')

In [7]:
?data = pd.date_range()
# dando um "help", consigo verificar todos os parametros desta função

In [8]:
mes = pd.date_range('20180101',periods =6,freq='M')
#Colocando o parâmetro freq='M', eu relaciono o período a meses em vez de dias. E ao que posso verificar ele sempre olha para o último 
# dia  de cada mês
mes

DatetimeIndex(['2018-01-31', '2018-02-28', '2018-03-31', '2018-04-30',
               '2018-05-31', '2018-06-30'],
              dtype='datetime64[ns]', freq='M')

In [9]:
ano = pd.date_range('20180101',periods =6,freq='Y')
#Colocando o parâmetro freq='Y', eu relaciono o período a ANOS em vez de dias ou meses. E ao que posso verificar ele sempre olha para o último 
# dia  do mês de dezembro de cada ano
ano

DatetimeIndex(['2018-12-31', '2019-12-31', '2020-12-31', '2021-12-31',
               '2022-12-31', '2023-12-31'],
              dtype='datetime64[ns]', freq='A-DEC')

In [10]:
type(ano)

pandas.core.indexes.datetimes.DatetimeIndex

Criando um Dataframe

In [11]:
np.random.randn(6,4)
# criando um array de 6 linhas e 4 colunas, preenchidos com números aleatórios.
#randn-> Gera números aleatórios

array([[-0.19827473,  0.00302235, -1.02337366, -1.06522914],
       [ 1.13339682, -1.07124685,  1.51901065, -0.08883988],
       [-0.62319252,  0.41981327, -0.44592679,  0.2547888 ],
       [ 0.58493658,  0.53462973,  0.98610202,  0.3126133 ],
       [ 0.59672421, -0.91317775, -1.65391636, -0.20535721],
       [ 0.05829844,  0.23766482, -0.38189632, -1.03904983]])

In [12]:
list('ABDC')
# criando uma lista

['A', 'B', 'D', 'C']

In [13]:
df = pd.DataFrame(np.random.randn(6,4),index= data,columns=list('ABDC'))

In [14]:
df
# dataframe montado com os indices que são as datas e as colunas são as letras 
#da lista

A         B         D         C
2018-01-01  0.531833  0.962496  1.488554  0.598472
2018-01-02  0.940038 -0.302766  0.994846 -0.141663
2018-01-03  2.017713 -0.462463  1.465562 -0.024839
2018-01-04 -1.031591  1.062323 -0.297366 -0.529969
2018-01-05  2.267238  0.102062 -1.264714  0.503936
2018-01-06  0.343097 -0.156067 -0.576795  0.688896

In [15]:
df2= pd.DataFrame({'A':7,
                   'B':pd.Timestamp('20190101'),
                   'C':pd.Series(1,index=list(range(4)), dtype= 'float32'),
                   'D':np.array([3]*4, dtype='int32'),
                   'E':pd.Categorical(['test','train','test','train']),
                   'E':'Python'})
# as letras A,B,C,D,E,F serão as colunas

In [16]:
df2

A          B    C  D       E
0  7 2019-01-01  1.0  3  Python
1  7 2019-01-01  1.0  3  Python
2  7 2019-01-01  1.0  3  Python
3  7 2019-01-01  1.0  3  Python

In [17]:
df2.dtypes
# verificando os tipos de dados contidos no dataframe

A             int64
B    datetime64[ns]
C           float32
D             int32
E            object
dtype: object

#Aula 2

Visualização de dados

In [19]:
df.head()
# por default mostra 5 linhas

A         B         D         C
2018-01-01  0.531833  0.962496  1.488554  0.598472
2018-01-02  0.940038 -0.302766  0.994846 -0.141663
2018-01-03  2.017713 -0.462463  1.465562 -0.024839
2018-01-04 -1.031591  1.062323 -0.297366 -0.529969
2018-01-05  2.267238  0.102062 -1.264714  0.503936

In [22]:
df.tail(2)
# este comando me permite veras últimas linhas do dataframe, assim com o head, se não colocarmos o número ele nos mostrará as 5 últimas linhas

A         B         D         C
2018-01-05  2.267238  0.102062 -1.264714  0.503936
2018-01-06  0.343097 -0.156067 -0.576795  0.688896

In [23]:
df.index
# retorna os índices do dataframe

DatetimeIndex(['2018-01-01', '2018-01-02', '2018-01-03', '2018-01-04',
               '2018-01-05', '2018-01-06'],
              dtype='datetime64[ns]', freq='D')

In [24]:
df.columns
# obtendo as colunas

Index(['A', 'B', 'D', 'C'], dtype='object')

In [26]:
c =df.columns
c
# armazenando as colunas em uma variável

Index(['A', 'B', 'D', 'C'], dtype='object')

In [27]:
df.to_numpy()
# pega somente os n´=umeros , ignorando colunas e indices, e cria uma matriz com os dados

array([[ 0.53183252,  0.96249625,  1.48855371,  0.59847225],
       [ 0.94003763, -0.30276611,  0.99484563, -0.14166324],
       [ 2.01771277, -0.46246335,  1.46556164, -0.02483879],
       [-1.03159096,  1.06232285, -0.29736627, -0.52996933],
       [ 2.26723806,  0.102062  , -1.26471399,  0.50393583],
       [ 0.34309718, -0.15606653, -0.57679488,  0.68889637]])

In [28]:
df.T
# da algebra linear, o T é de transposta e pega tudo o que for linha e transforma em coluna, e tudo que for coluna transforma em linha

2018-01-01  2018-01-02  2018-01-03  2018-01-04  2018-01-05  2018-01-06
A    0.531833    0.940038    2.017713   -1.031591    2.267238    0.343097
B    0.962496   -0.302766   -0.462463    1.062323    0.102062   -0.156067
D    1.488554    0.994846    1.465562   -0.297366   -1.264714   -0.576795
C    0.598472   -0.141663   -0.024839   -0.529969    0.503936    0.688896

In [29]:
df2.T

0  ...                    3
A                    7  ...                    7
B  2019-01-01 00:00:00  ...  2019-01-01 00:00:00
C                    1  ...                    1
D                    3  ...                    3
E               Python  ...               Python

[5 rows x 4 columns]

In [31]:
df2.to_numpy()

array([[7, Timestamp('2019-01-01 00:00:00'), 1.0, 3, 'Python'],
       [7, Timestamp('2019-01-01 00:00:00'), 1.0, 3, 'Python'],
       [7, Timestamp('2019-01-01 00:00:00'), 1.0, 3, 'Python'],
       [7, Timestamp('2019-01-01 00:00:00'), 1.0, 3, 'Python']],
      dtype=object)